export default [
  {
    custrecord_cop_af_trans: "14873229",
    custrecord_cop_amt: "100.00",
    custrecord_cop_amtremain: "0.00",
    custrecord_cop_fac: "653",
    custrecord_cop_inv: "1403073",
    custrecord_cop_res_appldamt: "0.00",
    custrecord_cop_res_refamt: "0.00",
    custrecord_cop_restype: "1",
    name: "OP000002"
  },
  {
    custrecord_cop_af_trans: "14873229",
    custrecord_cop_amt: "100.00",
    custrecord_cop_amtremain: "0.00",
    custrecord_cop_fac: "653",
    custrecord_cop_inv: "1403073",
    custrecord_cop_res_appldamt: "0.00",
    custrecord_cop_res_refamt: "0.00",
    custrecord_cop_restype: "1",
    name: "OP000003"
  },
  {
    custrecord_cop_af_trans: "14873229",
    custrecord_cop_amt: "100.00",
    custrecord_cop_amtremain: "0.00",
    custrecord_cop_fac: "663",
    custrecord_cop_inv: "1403073",
    custrecord_cop_res_appldamt: "0.00",
    custrecord_cop_res_refamt: "0.00",
    custrecord_cop_restype: "1",
    name: "OP000004"
  },
  {
    collapsed: false,
    custrecord_cop_inv: '5',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'Alta Bates Medical Center 0 Ashby',
    custrecord_cop_amt: '56,813.00',
    custrecord_cop_restype: '10',
    custrecord_cop_res_refamt: '56,813.00',
    custrecord_cop_res_appldamt: '4,551.17',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '32',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'Another Healthcare custrecord_cop_fac	',
    custrecord_cop_amt: '12,515.63',
    custrecord_cop_restype: '',
    custrecord_cop_res_refamt: '	12,515.63',
    custrecord_cop_res_appldamt: '	12,515.63',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '2',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'I Heart You custrecord_cop_fac	',
    custrecord_cop_amt: '23,561.34',
    custrecord_cop_restype: '10',
    custrecord_cop_res_refamt: '23,561.34',
    custrecord_cop_res_appldamt: '23,561.34',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '3',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'FlexCare custrecord_cop_fac',
    custrecord_cop_amt: '5,651.52',
    custrecord_cop_restype: '2',
    custrecord_cop_res_refamt: '5,651.52',
    custrecord_cop_res_appldamt: '5,651.52',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '5',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'FlexyCare custrecord_cop_fac',
    custrecord_cop_amt: '',
    custrecord_cop_restype: '8',
    custrecord_cop_res_refamt: '6,651.87',
    custrecord_cop_res_appldamt: '6,651.87',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '32',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'Mount Sinai West',
    custrecord_cop_amt: '43,346.74',
    custrecord_cop_restype: '5',
    custrecord_cop_res_refamt: '22,346.74',
    custrecord_cop_res_appldamt: '22,346.74',
    customer: '',
    children: [
      {
        custrecord_cop_inv: '2',
        custrecord_cop_af_trans: '5',
        weekending: '04/01/2023',
        custrecord_cop_fac: 'Mount Sinai West',
        custrecord_cop_amt: '4,271.40',
        custrecord_cop_restype: '',
        custrecord_cop_res_refamt: '3,330.47',
        custrecord_cop_res_appldamt: '3,337.44',
        customer: '',
      },
      {
        custrecord_cop_inv: '2',
        custrecord_cop_af_trans: '5',
        weekending: '04/08/2023',
        custrecord_cop_fac: 'Mount Sinai West',
        custrecord_cop_amt: '1,586.40',
        custrecord_cop_restype: '',
        custrecord_cop_res_refamt: '3,330.47',
        custrecord_cop_res_appldamt: '3,337.44',
        customer: '',
      },
      {
        custrecord_cop_inv: '1',
        custrecord_cop_af_trans: '5',
        weekending: '04/20/2023',
        custrecord_cop_fac: 'Mount Sinai West',
        custrecord_cop_amt: '5,324.23',
        custrecord_cop_restype: '',
        custrecord_cop_res_refamt: '3,330.47',
        custrecord_cop_res_appldamt: '3,337.44',
        customer: '',
      },
      {
        custrecord_cop_inv: '8',
        custrecord_cop_af_trans: '5',
        weekending: '04/27/2023',
        custrecord_cop_fac: 'Mount Sinai West',
        custrecord_cop_amt: '2,346.47',
        custrecord_cop_restype: '',
        custrecord_cop_res_refamt: '3,330.47',
        custrecord_cop_res_appldamt: '3,337.44',
        customer: '',
      },
    ],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '5',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'Alta Bates Medical Center 0 Ashby',
    custrecord_cop_amt: '56,813.00',
    custrecord_cop_restype: '10',
    custrecord_cop_res_refamt: '56,813.00',
    custrecord_cop_res_appldamt: '4,551.17',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '32',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'Another Healthcare custrecord_cop_fac	',
    custrecord_cop_amt: '12,515.63',
    custrecord_cop_restype: '',
    custrecord_cop_res_refamt: '	12,515.63',
    custrecord_cop_res_appldamt: '	12,515.63',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '2',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'I Heart You custrecord_cop_fac	',
    custrecord_cop_amt: '23,561.34',
    custrecord_cop_restype: '10',
    custrecord_cop_res_refamt: '23,561.34',
    custrecord_cop_res_appldamt: '23,561.34',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '3',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'FlexCare custrecord_cop_fac',
    custrecord_cop_amt: '5,651.52',
    custrecord_cop_restype: '2',
    custrecord_cop_res_refamt: '5,651.52',
    custrecord_cop_res_appldamt: '5,651.52',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '5',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'FlexyCare custrecord_cop_fac',
    custrecord_cop_amt: '',
    custrecord_cop_restype: '8',
    custrecord_cop_res_refamt: '6,651.87',
    custrecord_cop_res_appldamt: '6,651.87',
    customer: '',
    children: [],
  },
  {
    collapsed: false,
    custrecord_cop_inv: '32',
    custrecord_cop_af_trans: '',
    weekending: '',
    custrecord_cop_fac: 'Mount Sinai West',
    custrecord_cop_amt: '43,346.74',
    custrecord_cop_restype: '5',
    custrecord_cop_res_refamt: '22,346.74',
    custrecord_cop_res_appldamt: '22,346.74',
    customer: '',
    children: [
      {
        custrecord_cop_inv: '2',
        custrecord_cop_af_trans: '5',
        weekending: '04/01/2023',
        custrecord_cop_fac: 'Mount Sinai West',
        custrecord_cop_amt: '4,271.40',
        custrecord_cop_restype: '',
        custrecord_cop_res_refamt: '3,330.47',
        custrecord_cop_res_appldamt: '3,337.44',
        customer: '',
      },
      {
        custrecord_cop_inv: '2',
        custrecord_cop_af_trans: '5',
        weekending: '04/08/2023',
        custrecord_cop_fac: 'Mount Sinai West',
        custrecord_cop_amt: '1,586.40',
        custrecord_cop_restype: '',
        custrecord_cop_res_refamt: '3,330.47',
        custrecord_cop_res_appldamt: '3,337.44',
        customer: '',
      },
      {
        custrecord_cop_inv: '1',
        custrecord_cop_af_trans: '5',
        weekending: '04/20/2023',
        custrecord_cop_fac: 'Mount Sinai West',
        custrecord_cop_amt: '5,324.23',
        custrecord_cop_restype: '',
        custrecord_cop_res_refamt: '3,330.47',
        custrecord_cop_res_appldamt: '3,337.44',
        customer: '',
      },
      {
        custrecord_cop_inv: '8',
        custrecord_cop_af_trans: '5',
        weekending: '04/27/2023',
        custrecord_cop_fac: 'Mount Sinai West',
        custrecord_cop_amt: '2,346.47',
        custrecord_cop_restype: '',
        custrecord_cop_res_refamt: '3,330.47',
        custrecord_cop_res_appldamt: '3,337.44',
        customer: '',
      },
    ],
  },
]