export default [
  {
    tabName: 'Facility',
    headers: [
      { title: 'FACILITY', key: 'facility' },
      { title: '#', key: 'sharp' },
      { title: 'WEEK ENDING', key: 'weekending' },
      { title: 'INV PAID', key: 'invpaid' },
      { title: 'INVOICE #', key: 'invoice' },
      { title: 'INV DATE', key: 'invdate' },
      { title: 'INV TOTAL', key: 'invtotal' },
      { title: 'UNPAID AMT', key: 'unpaidamt' },
      { title: 'UNPAID NOTE', key: 'unpaidnote' },
      { title: 'MSP REF #', key: 'mspref' },
      { title: 'AMT DISPUTED', key: 'amtdisputed' },
      { title: 'DISPUTE NOTE', key: 'disputenote' },
      { title: 'PMT #', key: 'pmt' },
      { title: 'DEDUCT.AMT', key: 'deductamt' },
      { title: 'AMT RECEIVED', key: 'amtreceived' },
      { title: 'AMT APPLIED', key: 'amtapplied' },
    ],
    desserts: [
      {
        collapsed: false,
        children: [],
        facility: 'Alta Bates Medical Center - Ashby',
        sharp: '10',
        weekending: '',
        invpaid: '5',
        invoice: '',
        invdate: '',
        invtotal: '56,813.00',
        unpaidamt: '100.00',
        unpaidnote: '',
        mspref: '',
        amtdisputed: '',
        disputenote: '',
        pmt: '',
        deductamt: '',
        amtreceived: '56,813.00',
        amtapplied: '4,551.17',
      },
      {
        collapsed: false,
        children: [],
        facility: 'Another Healthcare Facility',
        sharp: '13',
        weekending: '',
        invpaid: '32',
        invoice: '',
        invdate: '',
        invtotal: '12,515.63',
        unpaidamt: '25.37',
        unpaidnote: '',
        mspref: '',
        amtdisputed: '',
        disputenote: '',
        pmt: '',
        deductamt: '',
        amtreceived: '12,515.63',
        amtapplied: '12,615.63',
      },
      {
        collapsed: false,
        children: [],
        facility: 'I Heart You Facility',
        sharp: '10',
        weekending: '',
        invpaid: '2',
        invoice: '',
        invdate: '',
        invtotal: '23,561.34',
        unpaidamt: '',
        unpaidnote: '',
        mspref: '',
        amtdisputed: '',
        disputenote: '',
        pmt: '',
        deductamt: '',
        amtreceived: '23,561.34',
        amtapplied: '23,561.34',
      },
      {
        collapsed: false,
        children: [],
        facility: 'FlexCare Facility',
        sharp: '2',
        weekending: '',
        invpaid: '3',
        invoice: '',
        invdate: '',
        invtotal: '5,651.52',
        unpaidamt: '',
        unpaidnote: '',
        mspref: '',
        amtdisputed: '',
        disputenote: '',
        pmt: '',
        deductamt: '',
        amtreceived: '5,651.52',
        amtapplied: '5,651.52',
      },
      {
        collapsed: false,
        children: [],
        facility: 'FlexyCare Facility',
        sharp: '8',
        weekending: '',
        invpaid: '5',
        invoice: '6,651.87',
        invdate: '',
        invtotal: '',
        unpaidamt: '',
        unpaidnote: '',
        mspref: '',
        amtdisputed: '',
        disputenote: '',
        pmt: '',
        deductamt: '',
        amtreceived: '6,651.87',
        amtapplied: '6,651.87',
      },
      {
        collapsed: true,
        children: [
          {
            facility: 'Mount Sinai West',
            sharp: '',
            weekending: '04/01/2023',
            invpaid: '2',
            invoice: 'IN4776313',
            invdate: '5',
            invtotal: '4,271.40',
            unpaidamt: '113.52',
            unpaidnote: '',
            mspref: '14639757',
            amtdisputed: '',
            disputenote: 'warn',
            pmt: '',
            deductamt: '',
            amtreceived: '3,330.47',
            amtapplied: '3,337.44',
          },
          {
            facility: 'Mount Sinai West',
            sharp: '',
            weekending: '04/01/2023',
            invpaid: '2',
            invoice: 'IN4776313',
            invdate: '5',
            invtotal: '4,271.40',
            unpaidamt: '113.52',
            unpaidnote: '',
            mspref: '14639757',
            amtdisputed: '',
            disputenote: 'warn',
            pmt: '',
            deductamt: '',
            amtreceived: '3,330.47',
            amtapplied: '3,337.44',
          },
          {
            facility: 'Mount Sinai West',
            sharp: '',
            weekending: '04/01/2023',
            invpaid: '2',
            invoice: 'IN4776313',
            invdate: '5',
            invtotal: '4,271.40',
            unpaidamt: '113.52',
            unpaidnote: '',
            mspref: '14639757',
            amtdisputed: '',
            disputenote: 'warn',
            pmt: '',
            deductamt: '',
            amtreceived: '3,330.47',
            amtapplied: '3,337.44',
          },
          {
            facility: 'Mount Sinai West',
            sharp: '',
            weekending: '04/01/2023',
            invpaid: '2',
            invoice: 'IN4776313',
            invdate: '5',
            invtotal: '4,271.40',
            unpaidamt: '113.52',
            unpaidnote: '',
            mspref: '14639757',
            amtdisputed: '',
            disputenote: 'warn',
            pmt: '',
            deductamt: '',
            amtreceived: '3,330.47',
            amtapplied: '3,337.44',
          },
        ],
        facility: 'Mount Sinai West',
        sharp: '5',
        weekending: '',
        invpaid: '32',
        invoice: '',
        invdate: '',
        invtotal: '43,346.74',
        unpaidamt: '1,845.13',
        unpaidnote: '',
        mspref: '',
        amtdisputed: '',
        disputenote: '',
        pmt: '',
        deductamt: '100.00',
        amtreceived: '22,346.74',
        amtapplied: '22,346.74'
      },
    ],
  },
  {
    tabName: 'Health System',
    headers: [
      { title: 'FACILITY', key: 'facility' },
      { title: '#', key: 'sharp' },
      { title: 'WEEK ENDING', key: 'weekending' },
      { title: 'INV PAID', key: 'invpaid' },
      { title: 'INVOICE #', key: 'invoice' },
      { title: 'INV DATE', key: 'invdate' },
      { title: 'INV TOTAL', key: 'invtotal' },
      { title: 'UNPAID AMT', key: 'unpaidamt' },
      { title: 'UNPAID NOTE', key: 'unpaidnote' },
      { title: 'MSP REF #', key: 'mspref' },
      { title: 'AMT DISPUTED', key: 'amtdisputed' },
      { title: 'DISPUTE NOTE', key: 'disputenote' },
      { title: 'PMT #', key: 'pmt' },
      { title: 'DEDUCT.AMT', key: 'deductamt' },
      { title: 'AMT RECEIVED', key: 'amtreceived' },
      { title: 'AMT APPLIED', key: 'amtapplied' },
    ],
    desserts: [],
  },
  {
    tabName: 'Week Ending',
    headers: [
      { title: 'WEEK ENDING', key: 'weekending' },
      { title: 'FACILITY', key: 'facility' },
      { title: '#', key: 'sharp' },
      { title: 'INV PAID', key: 'invpaid' },
      { title: 'INVOICE #', key: 'invoice' },
      { title: 'INV DATE', key: 'invdate' },
      { title: 'INV TOTAL', key: 'invtotal' },
      { title: 'UNPAID AMT', key: 'unpaidamt' },
      { title: 'UNPAID NOTE', key: 'unpaidnote' },
      { title: 'MSP REF #', key: 'mspref' },
      { title: 'AMT DISPUTED', key: 'amtdisputed' },
      { title: 'DISPUTE NOTE', key: 'disputenote' },
      { title: 'PMT #', key: 'pmt' },
      { title: 'DEDUCT.AMT', key: 'deductamt' },
      { title: 'AMT RECEIVED', key: 'amtreceived' },
      { title: 'AMT APPLIED', key: 'amtapplied' },
    ],
    desserts: [],
  },
  {
    tabName : 'Client Overpayment',
    headers: [
      { title: 'Overpaid Invoice', key: 'invoice' },
      { title: 'Overpaid Traveler', key: 'traveler' },
      { title: 'Overpaid Week Ending', key: 'weekending' },
      { title: 'Overpaid Facility', key: 'facility' },
      { title: 'Overpaid Amount', key: 'amount' },
      { title: 'Resolution Type', key: 'type' },
      { title: 'Resolution Refund Amount', key: 'refund' },
      { title: 'Resolution Applied Amount', key: 'applied' },
      { title: 'Customer Refund Transaction', key: 'customer' },
    ],
    desserts: [
      {
        collapsed: false,
        invoice: '5',
        traveler: '',
        weekending: '',
        facility: 'Alta Bates Medical Center 0 Ashby',
        amount: '56,813.00',
        type: '10',
        refund: '56,813.00',
        applied: '4,551.17',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '32',
        traveler: '',
        weekending: '',
        facility: 'Another Healthcare Facility	',
        amount: '12,515.63',
        type: '',
        refund: '	12,515.63',
        applied: '	12,515.63',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '2',
        traveler: '',
        weekending: '',
        facility: 'I Heart You Facility	',
        amount: '23,561.34',
        type: '10',
        refund: '23,561.34',
        applied: '23,561.34',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '3',
        traveler: '',
        weekending: '',
        facility: 'FlexCare Facility',
        amount: '5,651.52',
        type: '2',
        refund: '5,651.52',
        applied: '5,651.52',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '5',
        traveler: '',
        weekending: '',
        facility: 'FlexyCare Facility',
        amount: '',
        type: '8',
        refund: '6,651.87',
        applied: '6,651.87',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '32',
        traveler: '',
        weekending: '',
        facility: 'Mount Sinai West',
        amount: '43,346.74',
        type: '5',
        refund: '22,346.74',
        applied: '22,346.74',
        customer: '',
        children: [
          {
            invoice: '2',
            traveler: '5',
            weekending: '04/01/2023',
            facility: 'Mount Sinai West',
            amount: '4,271.40',
            type: '',
            refund: '3,330.47',
            applied: '3,337.44',
            customer: '',
          },
          {
            invoice: '2',
            traveler: '5',
            weekending: '04/08/2023',
            facility: 'Mount Sinai West',
            amount: '1,586.40',
            type: '',
            refund: '3,330.47',
            applied: '3,337.44',
            customer: '',
          },
          {
            invoice: '1',
            traveler: '5',
            weekending: '04/20/2023',
            facility: 'Mount Sinai West',
            amount: '5,324.23',
            type: '',
            refund: '3,330.47',
            applied: '3,337.44',
            customer: '',
          },
          {
            invoice: '8',
            traveler: '5',
            weekending: '04/27/2023',
            facility: 'Mount Sinai West',
            amount: '2,346.47',
            type: '',
            refund: '3,330.47',
            applied: '3,337.44',
            customer: '',
          },
        ],
      },
      {
        collapsed: false,
        invoice: '5',
        traveler: '',
        weekending: '',
        facility: 'Alta Bates Medical Center 0 Ashby',
        amount: '56,813.00',
        type: '10',
        refund: '56,813.00',
        applied: '4,551.17',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '32',
        traveler: '',
        weekending: '',
        facility: 'Another Healthcare Facility	',
        amount: '12,515.63',
        type: '',
        refund: '	12,515.63',
        applied: '	12,515.63',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '2',
        traveler: '',
        weekending: '',
        facility: 'I Heart You Facility	',
        amount: '23,561.34',
        type: '10',
        refund: '23,561.34',
        applied: '23,561.34',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '3',
        traveler: '',
        weekending: '',
        facility: 'FlexCare Facility',
        amount: '5,651.52',
        type: '2',
        refund: '5,651.52',
        applied: '5,651.52',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '5',
        traveler: '',
        weekending: '',
        facility: 'FlexyCare Facility',
        amount: '',
        type: '8',
        refund: '6,651.87',
        applied: '6,651.87',
        customer: '',
        children: [],
      },
      {
        collapsed: false,
        invoice: '32',
        traveler: '',
        weekending: '',
        facility: 'Mount Sinai West',
        amount: '43,346.74',
        type: '5',
        refund: '22,346.74',
        applied: '22,346.74',
        customer: '',
        children: [
          {
            invoice: '2',
            traveler: '5',
            weekending: '04/01/2023',
            facility: 'Mount Sinai West',
            amount: '4,271.40',
            type: '',
            refund: '3,330.47',
            applied: '3,337.44',
            customer: '',
          },
          {
            invoice: '2',
            traveler: '5',
            weekending: '04/08/2023',
            facility: 'Mount Sinai West',
            amount: '1,586.40',
            type: '',
            refund: '3,330.47',
            applied: '3,337.44',
            customer: '',
          },
          {
            invoice: '1',
            traveler: '5',
            weekending: '04/20/2023',
            facility: 'Mount Sinai West',
            amount: '5,324.23',
            type: '',
            refund: '3,330.47',
            applied: '3,337.44',
            customer: '',
          },
          {
            invoice: '8',
            traveler: '5',
            weekending: '04/27/2023',
            facility: 'Mount Sinai West',
            amount: '2,346.47',
            type: '',
            refund: '3,330.47',
            applied: '3,337.44',
            customer: '',
          },
        ],
      },
    ],
  },
  {
    tabName : 'Existing Insufficient Funds',
    headers: [
      { title: 'Insufficient Funds Transaction', key: 'transaction' },
      { title: 'Insufficient Funds Check / Payment #', key: 'check' },
      { title: 'Insufficient Funds Amount', key: 'amount' },
    ],
    desserts: [],
  },
  {
    tabName : 'Existing Applied To Invoice',
    headers: [
      { title: 'Appled To Invoice', key: 'invoice' },
      { title: 'Applied To Traveler', key: 'traveler' },
      { title: 'Applied To Week Ending', key: 'weekending' },
      { title: 'Applied to Facility', key: 'facility' },
      { title: 'Applied to Amount', key: 'amount' },
    ],
    desserts: [],
  },
];