export default {
  facility: [
    {
      collapsed: false,
      tppdi: '174',
      custrecord_fc_tppdi_designatedinvoice: '8990202',
      custrecord_fc_tppdi_designatedinvoice_txt: 'Invoice #IN32996502',
      custrecord_fc_tppdi_thirdpartypayment: '9582694',
      custrecord_fc_tppdi_thirdpartypayment_txt: 'Third Party Payment #TPP100001',
      custrecord_fc_tppdi_disbursementpayment: '9600587',
      custrecord_fc_tppdi_disbursementpayment_txt: 'Payment #P100200',
      custrecord_fc_tppdi_tpp_disburse_amount: '4159.81',
      custrecord_fc_tppdi_dp_deduct_item: '',
      custrecord_fc_tppdi_dp_deduct_item_txt: '',
      custrecord_fc_tppdi_dp_deduct_amount: '',
      custrecord_fc_tppdi_di_total_appl: '',
      custrecord_fc_tppdi_di_dispute_amount: '',
      custrecord_fc_tppdi_tpp_payor: 'CL01632 Supplemental Healthcare',
      custrecord_fc_tppdi_di_client: '1165',
      custrecord_fc_tppdi_di_client_txt: 'CL01057 Lancaster General Hospital',
      custrecord_fc_tppdi_di_msp: 'Supplemental Healthcare',
      custrecord_fc_tppdi_di_tranid: 'IN32996502',
      custrecord_fc_tppdi_di_invrefnum: '',
      custrecord_fc_tppdi_di_date: '12/29/2021',
      custrecord_fc_tppdi_di_total: '4159.81',
      custrecord_fc_tppdi_di_aracct: '213',
      custrecord_fc_tppdi_di_aracct_txt: '11010 Accounts Receivable : Accounts Receivable Trade',
      custrecord_fc_tppdi_di_unpaid_amount: '.00',
      custrecord_fc_tppdi_di_unpaid_note: '',
      custrecord_fc_tppdi_di_dispute_note: '',
      custrecord_fc_tppdi_dp_tranid: 'P100200',
      custrecord_fc_tppdi_dp_net_applied: '4159.81',
      internalid: '8990202',
      internalid_txt: '8990202',
      total: '4159.81',
      amountpaid: '.00',
      tranid: 'IN32996502',
      entity: '369477',
      entity_txt: 'AC37193 Lancaster General Hospital : OC-000051911',
      trandate: '12/29/2021',
      enddate: '',
      amountremaining: '',
      custbody__pi_msp_ref_number: '',
      custbody__pi_inv_traveler: '3243',
      custbody__pi_inv_traveler_txt: 'Christopher Jaeger A5LU',
      custbody_fc_unpaid_note: ''
    },
  ],
  health: [],
  weekending: [],
  insfund: [],
}