export default data = {
  headers: [
    {
      title: 'FACILITY',
      align: 'start',
      sortable: false,
      key: 'facility'
    },
    { title: '#', key: 'sharp' },
    { title: 'WEEK ENDING', key: 'weekending' },
    { title: 'INV PAID', key: 'invpaid' },
    { title: 'INVOICE #', key: 'invoice' },
    { title: 'INV DATE', key: 'invdate' },
    { title: 'INV TOTAL', key: 'invtotal' },
    { title: 'UNPAID AMT', key: 'unpaidamt' },
    { title: 'UNPAID NOTE', key: 'unpaidnote' },
    { title: 'MSP REF #', key: 'mspref' },
    { title: 'AMT DISPUTED', key: 'amtdisputed' },
    { title: 'DISPUTE NOTE', key: 'disputenote' },
    { title: 'PMT #', key: 'pmt' },
    { title: 'DEDUCT.AMT', key: 'deductamt' },
    { title: 'AMT RECEIVED', key: 'amtreceived' },
    { title: 'AMT APPLIED', key: 'amtapplied' },
  ],
  desserts: [
    {
      collapsed: false,
      children: [],
      facility: 'Alta Bates Medical Center - Ashby',
      sharp: '10',
      weekending: '',
      invpaid: '5',
      invoice: '',
      invdate: '',
      invtotal: '56,813.00',
      unpaidamt: '100.00',
      unpaidnote: '',
      mspref: '',
      amtdisputed: '',
      disputenote: '',
      pmt: '',
      deductamt: '',
      amtreceived: '56,813.00',
      amtapplied: '4,551.17',
    },
    {
      collapsed: false,
      children: [],
      facility: 'Another Healthcare Facility',
      sharp: '13',
      weekending: '',
      invpaid: '32',
      invoice: '',
      invdate: '',
      invtotal: '12,515.63',
      unpaidamt: '25.37',
      unpaidnote: '',
      mspref: '',
      amtdisputed: '',
      disputenote: '',
      pmt: '',
      deductamt: '',
      amtreceived: '12,515.63',
      amtapplied: '12,615.63',
    },
    {
      collapsed: false,
      children: [],
      facility: 'I Heart You Facility',
      sharp: '10',
      weekending: '',
      invpaid: '2',
      invoice: '',
      invdate: '',
      invtotal: '23,561.34',
      unpaidamt: '',
      unpaidnote: '',
      mspref: '',
      amtdisputed: '',
      disputenote: '',
      pmt: '',
      deductamt: '',
      amtreceived: '23,561.34',
      amtapplied: '23,561.34',
    },
    {
      collapsed: false,
      children: [],
      facility: 'FlexCare Facility',
      sharp: '2',
      weekending: '',
      invpaid: '3',
      invoice: '',
      invdate: '',
      invtotal: '5,651.52',
      unpaidamt: '',
      unpaidnote: '',
      mspref: '',
      amtdisputed: '',
      disputenote: '',
      pmt: '',
      deductamt: '',
      amtreceived: '5,651.52',
      amtapplied: '5,651.52',
    },
    {
      collapsed: false,
      children: [],
      facility: 'FlexyCare Facility',
      sharp: '8',
      weekending: '',
      invpaid: '5',
      invoice: '6,651.87',
      invdate: '',
      invtotal: '',
      unpaidamt: '',
      unpaidnote: '',
      mspref: '',
      amtdisputed: '',
      disputenote: '',
      pmt: '',
      deductamt: '',
      amtreceived: '6,651.87',
      amtapplied: '6,651.87',
    },
    {
      collapsed: true,
      children: [
        {
          facility: 'Mount Sinai West',
          sharp: '',
          weekending: '04/01/2023',
          invpaid: '2',
          invoice: 'IN4776313',
          invdate: '5',
          invtotal: '4,271.40',
          unpaidamt: '113.52',
          unpaidnote: '',
          mspref: '14639757',
          amtdisputed: '',
          disputenote: 'warn',
          pmt: '',
          deductamt: '',
          amtreceived: '3,330.47',
          amtapplied: '3,337.44',
        },
        {
          facility: 'Mount Sinai West',
          sharp: '',
          weekending: '04/01/2023',
          invpaid: '2',
          invoice: 'IN4776313',
          invdate: '5',
          invtotal: '4,271.40',
          unpaidamt: '113.52',
          unpaidnote: '',
          mspref: '14639757',
          amtdisputed: '',
          disputenote: 'warn',
          pmt: '',
          deductamt: '',
          amtreceived: '3,330.47',
          amtapplied: '3,337.44',
        },
        {
          facility: 'Mount Sinai West',
          sharp: '',
          weekending: '04/01/2023',
          invpaid: '2',
          invoice: 'IN4776313',
          invdate: '5',
          invtotal: '4,271.40',
          unpaidamt: '113.52',
          unpaidnote: '',
          mspref: '14639757',
          amtdisputed: '',
          disputenote: 'warn',
          pmt: '',
          deductamt: '',
          amtreceived: '3,330.47',
          amtapplied: '3,337.44',
        },
        {
          facility: 'Mount Sinai West',
          sharp: '',
          weekending: '04/01/2023',
          invpaid: '2',
          invoice: 'IN4776313',
          invdate: '5',
          invtotal: '4,271.40',
          unpaidamt: '113.52',
          unpaidnote: '',
          mspref: '14639757',
          amtdisputed: '',
          disputenote: 'warn',
          pmt: '',
          deductamt: '',
          amtreceived: '3,330.47',
          amtapplied: '3,337.44',
        },
      ],
      facility: 'Mount Sinai West',
      sharp: '5',
      weekending: '',
      invpaid: '32',
      invoice: '',
      invdate: '',
      invtotal: '43,346.74',
      unpaidamt: '1,845.13',
      unpaidnote: '',
      mspref: '',
      amtdisputed: '',
      disputenote: '',
      pmt: '',
      deductamt: '100.00',
      amtreceived: '22,346.74',
      amtapplied: '22,346.74'
    },
  ],
}