export default {
  tranid: 'TPP100003',
  memo: 'C&A AP/VNDR PMT Amer Nat C 0000013596 RMR*IV*006635**1304384.58\\',
  custbody_fc_tpp_lastautosave: '05/29/2023 6:13:27 pm',
  custbody_fc_tpp_lastautosaveby: '',
  custbody_fc_tpp_lastmodified: '',
  custbody_fc_tpp_lastmodifiedby: '',
  custbody__pi_msp: '536',
  custbody_fc_tpp_original_pay_customer: '',
  custbody_fc_tpp_original_pay_reference: 'Ref #&nbsp;&nbsp;&nbsp; : Amt $',
  custbody_fc_tpp_resarch_hold_ck: false,
  custbody_fc_tpp_amount_remain: '',
  custbody_fc_tpp_aracct: '11010 Accounts Receivable : Accounts Receivable Trade',
  custbody_fc_tpp_cashaccount: '10030 Cash & Cash Equivalents : WF Lockbox 8503',
  custbody_fc_tpp_paymentamount: '1304384.58',
  custbody_fc_tpp_paymentnum: 'IA000850013762',
  custbody_fc_tpp_payor: 'CL00428 FocusOne',
  custbody_fc_tpp_payor_clienttype: 'MSP',
  custbody_fc_likelyapplication: '',
  custbody_fc_likelyrefund: '',
  custbody_fc_researchrequiredamount_tpp: 'ERROR: Invalid Expression',
  cseg_fc_msp: '18'
};
